print('=== Desafio 02 ===')
dia = input('Em que dia você nasceu? ')
mes = input('Em que mês você nasceu? ')
ano = input('Em que ano você nasceu? ')
print('Sua data de nascimento é', dia ,'de', mes, 'de', ano, '. Correto?')
